version: "3.8"

networks:
  nodets-network:
    driver: bridge

services:
  app:
    build: .
    container_name: nodets
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - MONGO_URL=nodets-mongodb
      - REDIS_URL=nodets-redis
    depends_on:
      - nodets-mongodb
      - nodets-redis
    networks:
      - nodets-network
    links:
      - nodets-mongodb
      - nodets-redis
    command: yarn dev

  nodets-mongodb:
    image: bitnami/mongodb:5.0
    container_name: nodets-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_USERNAME=${MONGO_USER}
      - MONGODB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    volumes:
      - data:/data/bitnami/mongodb/data
    networks:
      - nodets-network

  nodets-redis:
    image: bitnami/redis:latest
    container_name: nodets-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - data:/data/bitnami/redis/data
    networks:
      - nodets-network

volumes:
  node_modules:
  data:
